/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors avoid a Vinext client navigation runtime failure. */
import Image from 'next/image';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { JsonLd } from '../../json-ld';
import { absoluteUrl, siteUrl } from '../../site-config';

const projects = {
  'public-health-surveillance': { title:'Public Health Surveillance Analytics Dashboard', tool:'Power BI', image:'/images/analytics/public-health-surveillance.jpg', objective:'Explore how surveillance indicators can be structured into a clear monitoring view for faster interpretation of disease patterns and programme signals.', approach:'Organised epidemiological indicators into a concise KPI layer, comparative state views, disease breakdowns and date-based filtering to support structured analytical review.', skills:['Epidemiological analysis','CFR calculation','KPI development','Disease trend monitoring','Interactive filtering','Power BI visualization'], disclaimer:'Developed using publicly available open-source data for analytical and visualization purposes. This is not an official national surveillance report and is not affiliated with any government agency or public-health institution.' },
  'hospital-admissions': { title:'Hospital Admissions Analytics Dashboard', tool:'Power BI', image:'/images/analytics/hospital-admissions.jpg', objective:'Demonstrate a clear analytical view of admissions activity, patient demographics and diagnosis patterns using a healthcare-themed practice dataset.', approach:'Built summary indicators and comparative views for time trends, age groups, gender and diagnosis categories, with filtering designed to support exploratory analysis.', skills:['Healthcare analytics','Admission trends','Demographic analysis','Diagnosis analysis','KPI reporting','Power BI visualization'], disclaimer:'Independent data analytics project created for analytical and visualization practice. It does not represent an identified hospital or official institutional report.' },
  'breast-cancer-tableau': { title:'Breast Cancer Analytics Dashboard', tool:'Tableau', image:'/images/analytics/breast-cancer-tableau.jpg', objective:'Present a focused analytical view of cancer stage, surgery type, patient status and mortality indicators.', approach:'Structured patient and treatment dimensions into comparative charts and high-level indicators, using dashboard filters to support focused review.', skills:['Health analytics','Cancer-stage analysis','Patient-status analysis','Surgery analysis','Mortality indicators','Tableau visualization'], disclaimer:'Independent data analytics project created for analytical and visualization practice. It is not presented as an official clinical or institutional report.' },
  'emerald-properties-conversion': { title:'Emerald Properties Conversion Analysis', tool:'Microsoft Excel', image:'/images/analytics/emerald-properties-conversion.jpg', objective:'Demonstrate how sales and lead data can be translated into a practical view of conversion performance beyond the health sector.', approach:'Compared leads, sales, conversion rates, branches, inspections and product categories in a concise Excel dashboard designed for operational review.', skills:['Lead conversion','Sales performance','KPI analysis','Branch comparison','Inspection analysis','Excel dashboards'], disclaimer:'Independent business analytics project created for analytical and visualization practice. No affiliation with a real property organisation is claimed.' },
} as const;

export function generateStaticParams(){return Object.keys(projects).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects[slug as keyof typeof projects];const path=`/analytics/${slug}`;return p?{title:p.title,description:p.objective,alternates:{canonical:path},openGraph:{title:`${p.title} | Omobolanle Adelekun`,description:p.objective,type:'article',url:path,images:[]},twitter:{card:'summary',title:`${p.title} | Omobolanle Adelekun`,description:p.objective,images:[]}}:{}}
export default async function AnalyticsProject({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects[slug as keyof typeof projects];if(!p)notFound();const pageUrl=absoluteUrl(`/analytics/${slug}`);const schema=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl},{'@type':'ListItem',position:2,name:'Data Analytics Projects',item:absoluteUrl('/#analytics')},{'@type':'ListItem',position:3,name:p.title,item:pageUrl}]},{'@context':'https://schema.org','@type':'CreativeWork','@id':`${pageUrl}#project`,name:p.title,description:p.objective,url:pageUrl,inLanguage:'en',creator:{'@type':'Person','@id':`${siteUrl}/#person`,name:'Omobolanle Esther Adelekun'},keywords:p.skills}];return <main className="analyticsDetail"><JsonLd data={schema}/><header><a href="/#analytics">← Back to analytics</a><span>Independent Data Analytics Project</span></header><section className="analyticsHero"><p className="eyebrow">Independent Data Analytics Project · {p.tool}</p><h1>{p.title}</h1></section><section className="analyticsShowcase"><a href={p.image} target="_blank" rel="noopener noreferrer" aria-label={`Open the full-size ${p.title} dashboard image in a new tab`}><div className="analyticsLargeImage"><Image src={p.image} fill priority sizes="100vw" alt={`Full dashboard view of ${p.title}`} /></div><span>Open full-size dashboard →</span></a></section><section className="analyticsDetails"><article><h2>Project objective</h2><p>{p.objective}</p><h2>Analytical approach</h2><p>{p.approach}</p><h2>Skills demonstrated</h2><div className="tags">{p.skills.map(skill=><span key={skill}>{skill}</span>)}</div><div className="analyticsDisclaimer"><b>Project context</b><p>{p.disclaimer}</p></div><a className="button" href="/#analytics">Back to analytics <span>↖</span></a></article><aside><p className="eyebrow">Project details</p><p><b>Tool</b>{p.tool}</p><p><b>Type</b>Independent Data Analytics Project</p></aside></section></main>}
