import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';

const studies = {
  'idsr-outbreak-preparedness-bayelsa': { title:'Strengthening IDSR & Outbreak Preparedness in Bayelsa', org:'World Health Organization', location:'Bayelsa State, Nigeria', period:'January 2024 – October 2025', tags:['Global Health Security','Disease Surveillance','Immunization','Health Systems Strengthening'], context:'Strong surveillance and preparedness systems depend on consistent reporting, capable teams and coordinated action. This assignment supported integrated disease surveillance, emergency preparedness and response across Bayelsa State.', role:'As Sub-National Technical Assistant for IDSR / Emergency Preparedness & Response, Omobolanle supported surveillance, immunization and outbreak-response activities, while strengthening capacity and coordination across the system.', approach:['Supported IDSR, vaccine-preventable disease and AEFI surveillance activities.','Contributed to preparedness and response work for measles, yellow fever, Oral Cholera Vaccine, Mpox and OPV interventions.','Supported data use through DHIS2 and evidence review.','Strengthened workforce capacity and stakeholder coordination.'], outcome:'More than 5,000 health personnel were reached through capacity-strengthening activities across surveillance, immunization and outbreak response.', tools:'DHIS2 · IDSR · AEFI surveillance · Technical reporting · Supportive supervision' },
  'measles-rubella-lagos': { title:'Measles-Rubella Vaccine Introduction, Lagos', org:'World Health Organization', location:'Lagos State, Nigeria', period:'January 2026 – April 2026', tags:['Immunization','Vaccine Introduction','Monitoring & Evaluation','Health Systems Strengthening'], context:'Introducing a vaccine at scale requires careful planning, workforce readiness, field monitoring and collaboration across multiple levels of the health system.', role:'As Technical Officer for Measles-Rubella Vaccine Introduction, Omobolanle supported campaign planning, microplanning, implementation, field monitoring, supportive supervision and stakeholder engagement.', approach:['Supported vaccination campaign planning and microplanning.','Contributed to training and readiness of vaccination teams.','Provided field monitoring and supportive supervision.','Supported implementation review and stakeholder engagement.'], outcome:'1,068 Measles-Rubella vaccination team members were trained and supervised. No unverified coverage result is attributed to this assignment.', tools:'Vaccination microplanning · Field monitoring · Supportive supervision · Technical reporting' },
  'avadar-afp-kwara': { title:'AVADAR & AFP Surveillance, Kwara', org:'World Health Organization', location:'Kwara State, Nigeria', period:'January 2022 – December 2023', tags:['Disease Surveillance','Data & Digital Health','Monitoring & Evaluation','AFP Surveillance'], context:'Acute flaccid paralysis surveillance relies on timely, complete and high-quality information from a wide network of health facilities. The AVADAR project added a digital-health dimension to this work.', role:'As State Data Assistant, Omobolanle supported surveillance data management, data quality, dashboards, evidence review and performance monitoring across the facility network.', approach:['Supported AFP surveillance data management and routine quality review.','Monitored reporting and performance across participating facilities.','Used dashboards and evidence review to support programme decisions.','Supported health-information-system workflows and technical reporting.'], outcome:'Surveillance data work covered more than 713 health facilities in Kwara State.', tools:'AVADAR · Surveillance dashboards · Data quality review · Performance monitoring · Technical reporting' },
} as const;

const whoPublicationUrl = 'https://www.afro.who.int/fr/node/19767';
const whoBulletinUrl = 'https://www.afro.who.int/sites/default/files/2024-08/Cholera%20Snapshot%20Bulletin%20-%2018%20-%2031%20July%202024.pdf';

function CholeraEvidence(){return <section className="choleraEvidence" aria-labelledby="cholera-evidence-title"><div className="evidenceIntro"><p className="eyebrow">Official WHO documentation</p><h2 id="cholera-evidence-title">From the Field: WHO Cholera Response</h2><p>During my WHO assignment in Bayelsa State, I contributed to disease surveillance and outbreak-response activities during the cholera response. WHO Nigeria&apos;s official EPR Snapshot Bulletin documents response activities in Bayelsa, including active case search in Famgbe and AVoC-SURGE engagement with state leadership. Field photographs I captured during the response were selected for publication in the bulletin and credited by WHO.</p></div><div className="evidenceGrid"><figure><div className="evidenceImage"><Image src="/images/evidence/cholera-active-case-search-famgbe.jpg" fill sizes="(max-width: 760px) 100vw, 32vw" alt="WHO and NCDC experts conducting active cholera case search activities in Famgbe, Bayelsa State." /></div><figcaption><h3>Active Case Search, Famgbe</h3><p>WHO and NCDC experts conducting active case searches in Famgbe, Bayelsa State.</p><span>© WHO/Bolanle Esther</span><small>Published in the bulletin&apos;s Health Information Management, Surveillance and Laboratory section.</small></figcaption></figure><figure><div className="evidenceImage"><Image src="/images/evidence/cholera-avoc-surge-bayelsa.jpg" fill sizes="(max-width: 760px) 100vw, 32vw" alt="AVoC-SURGE team briefing the Bayelsa State Commissioner for Health during the cholera response." /></div><figcaption><h3>AVoC-SURGE Coordination, Bayelsa</h3><p>AVoC-SURGE team briefing the Honourable Commissioner for Health, Bayelsa State.</p><span>© WHO/Bolanle Esther</span><small>Published in the bulletin&apos;s AVoC-SURGE Initiative section.</small></figcaption></figure></div><aside className="evidenceCallout"><div><b>Field documentation published and credited by WHO Nigeria</b><p>Two photographs documenting cholera-response activities in Bayelsa were published in WHO Nigeria&apos;s July 2024 EPR Snapshot Bulletin with the credit © WHO/Bolanle Esther.</p></div><div className="evidenceActions"><a className="button" href={whoPublicationUrl} target="_blank" rel="noopener noreferrer" aria-label="View the official WHO Nigeria Cholera Snapshot Bulletin publication page in a new tab">View Official WHO Publication →</a><a className="evidenceSecondary" href={whoBulletinUrl} target="_blank" rel="noopener noreferrer" aria-label="View the official WHO Nigeria EPR Snapshot Bulletin PDF in a new tab">View Bulletin PDF →</a></div></aside></section>}

export function generateStaticParams(){return Object.keys(studies).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=studies[slug as keyof typeof studies];return s?{title:`${s.title} | Omobolanle Adelekun`,description:s.context,openGraph:{title:s.title,description:s.context,images:[]},twitter:{title:s.title,description:s.context,images:[]}}:{}}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=studies[slug as keyof typeof studies];if(!s)notFound();return <main className="study"><header><Link href="/#work">← Back to projects</Link><span>Professional field experience</span></header><section className="studyHero"><p className="eyebrow">Case study · {s.location}</p><h1>{s.title}</h1><div className="studyMeta"><p><b>Organisation</b>{s.org}</p><p><b>Location</b>{s.location}</p><p><b>Period</b>{s.period}</p></div><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div></section><div className="studyBody"><aside><p className="eyebrow">At a glance</p><p>{s.outcome}</p></aside><article><h2>Context</h2><p>{s.context}</p><h2>Role & scope</h2><p>{s.role}</p><h2>Approach</h2><ul>{s.approach.map(a=><li key={a}>{a}</li>)}</ul><h2>Contribution / outcomes</h2><p>{s.outcome}</p>{slug==='idsr-outbreak-preparedness-bayelsa'&&<CholeraEvidence/>}<h2>Tools & methods</h2><p>{s.tools}</p><Link className="button" href="/#work">Back to projects <span>↖</span></Link></article></div></main>}
