/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors preserve reliable Vinext navigation. */
import type { Metadata } from 'next';
import { weekly, diseases, ages, capabilities } from './data';
import '../../analytics-intelligence.css';

const title='Disease Surveillance & Outbreak Intelligence';
const description='An independent analytical case study using simulated surveillance data to assess quality, detect unusual disease signals and prioritize public-health investigation.';
const path='/analytics/disease-surveillance-outbreak-intelligence';
const socialImage = '/images/social/disease-surveillance-outbreak-intelligence.png';
export const metadata:Metadata={title,description,alternates:{canonical:path},openGraph:{title,description,url:path,type:'article',images:[{url:socialImage,width:1200,height:630,alt:`${title} — Omobolanle Esther Adelekun`}]},twitter:{title,description,card:'summary_large_image',images:[socialImage]}};

function Trend(){const x=(week:number)=>(week-.5)*30;const y=(value:number)=>250-value*5;const line=weekly.filter(row=>row[4]!==null).map(([week,,,,threshold])=>`${x(week)},${y(threshold!)}`).join(' ');return <figure className="intelligenceTrend">
  <div className="intelligenceLegend"><span><i className="caseKey"/>Weekly cases</span><span><i className="thresholdKey"/>Rolling signal threshold</span></div>
  <div className="intelligencePlot"><div className="intelligenceYAxis" aria-hidden="true"><span>50</span><span>25</span><span>0</span></div><div className="intelligenceChartCanvas"><svg viewBox="0 0 780 250" preserveAspectRatio="none" role="img" aria-labelledby="trend-title trend-description"><title id="trend-title">Weekly cholera cases and rolling signal threshold, EW1–26</title><desc id="trend-description">Cases exceed the threshold in EW15, EW16 and EW22. EW16 peaks at 36 cases against a threshold of 12.97. All weekly values are available in the expandable table below.</desc><path d="M0 125H780 M0 249H780" stroke="var(--line)" fill="none" vectorEffect="non-scaling-stroke"/>{weekly.map(([week,cases])=><rect key={week} x={x(week)-10} y={y(cases)} width="20" height={cases*5} fill={week===15||week===16?'var(--navy)':'var(--teal)'}><title>{`EW${week}: ${cases} cases`}</title></rect>)}<polyline points={line} fill="none" stroke="var(--navy)" strokeWidth="2" strokeDasharray="5 4" vectorEffect="non-scaling-stroke"/>{[15,16,22].map(week=><circle key={week} cx={x(week)} cy={y(weekly[week-1][1])-5} r="3" fill="var(--navy)"/>)}</svg><div className="intelligenceAnnotation intelligenceAnnotationFirst"><b>EW15</b><span>First threshold exceedance</span></div><div className="intelligenceAnnotation intelligenceAnnotationPeak"><b>EW16</b><span>36 cases · 3 deaths</span></div></div><div className="intelligenceXTicks" aria-hidden="true">{[1,5,10,15,20,26].map(week=><span key={week} style={{left:`${(week-.5)/26*100}%`}}>{week}</span>)}</div></div>
  <figcaption>Epidemiological week · Dots mark threshold exceedances. EW1–4 have no threshold because four preceding weeks are required.</figcaption>
</figure>}

export default function SurveillanceAnalysis(){return <main className="intelligencePage" id="analysis-main">
  <a className="skip" href="#analysis-question">Skip to analysis</a><header className="intelligenceNav"><a href="/#analytics">← Back to analytics</a><span>Independent analytical project</span></header>
  <section className="intelligenceHero"><p className="eyebrow">Public Health Analytics &amp; Decision Intelligence</p><h1>{title}</h1><p className="intelligenceSubtitle">Subnational epidemiological analysis for early detection and public-health decision-making.</p><div className="intelligenceHeroFoot"><span>Simulated data · Fictionalized geography</span><span>Epidemiological analysis · Decision support</span></div></section>
  <div className="intelligenceStory">
    <section className="intelligenceSection" id="analysis-question"><p className="eyebrow">01 / The question</p><h2>Can routine data reveal an emerging signal early enough to act?</h2><p className="intelligenceLead">Look beyond the case count: check the data, locate the unusual increase, and decide what needs investigation first.</p></section>
    <section className="intelligenceSection"><p className="eyebrow">02 / The data</p><h2>A simulated surveillance setting.</h2><p>This analysis uses a simulated, de-identified surveillance dataset structured to reflect routine subnational disease-surveillance workflows. Geographic and facility identifiers are fictionalized. No patient-identifiable or confidential programme data are included.</p><dl className="intelligenceMetrics"><div><dt>Analysis-ready records</dt><dd>696</dd></div><div><dt>Epidemiological weeks</dt><dd>26</dd></div><div><dt>Diseases analysed</dt><dd>4</dd></div></dl><p className="intelligenceNote">All cases, deaths and signals are simulated scenarios, not actual events in a real jurisdiction.</p></section>
    <section className="intelligenceSection"><p className="eyebrow">03 / Data quality</p><h2>Make the evidence usable first.</h2><div className="intelligenceQualityFlow"><div><strong>716</strong><span>raw records preserved</span></div><span aria-hidden="true">→</span><div><strong>696</strong><span>analysis-ready records</span></div></div><ul className="intelligenceQuality"><li><strong>8 duplicate case IDs identified</strong><span>16 affected rows; 8 duplicate copies excluded.</span></li><li><strong>12 implausible ages</strong><span>Flagged and excluded from the core analysis. No imputation.</span></li><li><strong>18 missing lab results</strong><span>Kept distinct from pending and not-collected results.</span></li></ul><p className="intelligenceNote">20 records excluded in total. Raw records and quality flags remain available in the analytical workflow.</p></section>
    <section className="intelligenceSection"><p className="eyebrow">04 / Person, place &amp; time</p><h2>Burden and severity tell different stories.</h2><div className="intelligenceTwoCol"><figure className="intelligenceBars"><h3>Reported disease burden</h3><p className="intelligenceNote">Eligible cases · Observed case fatality ratio (CFR)</p>{diseases.map(d=><div className="intelligenceBarRow" key={d.name}><div><b>{d.name}</b><span>{d.cases} cases · {d.cfr} CFR</span></div><div className="intelligenceBarTrack" aria-hidden="true"><span style={{width:`${d.cases/366*100}%`}}/></div></div>)}<figcaption>Measles has the largest burden; Lassa fever has the highest observed CFR. CFR reflects recorded outcomes, not population risk.</figcaption></figure><figure className="intelligenceBars"><h3>Age distribution</h3><p className="intelligenceNote">Years · Eligible cases</p>{ages.map(([age,count])=><div className="intelligenceAgeRow" key={age}><span>{age}</span><div className="intelligenceBarTrack" aria-hidden="true"><span style={{width:`${count/167*100}%`}}/></div><b>{count}</b></div>)}<figcaption>Most records are in ages 15–24 and 25–34. Sex distribution: 358 male, 338 female.</figcaption></figure></div></section>
    <section className="intelligenceSection"><p className="eyebrow">05 / The outbreak signal</p><h2>A sharp increase at EW16.</h2><p>EW15 is the first threshold exceedance. EW16 strengthens the signal, with 36 cases and 3 deaths.</p><Trend/><div className="intelligenceSignalNotes">{[[15,'12','5.50','7.74','0'],[16,'36','6.75','12.97','3'],[22,'10','4.75','9.73','1']].map(([week,cases,mean,threshold,deaths])=><div key={week}><h3>EW{week}</h3><strong>{cases} cases</strong><p>{deaths} deaths · Mean {mean}<br/>Threshold {threshold}</p></div>)}</div><details className="intelligenceDetails"><summary>Method and all weekly values</summary><p>The threshold is the preceding four complete weeks’ mean + 2 standard deviations. The current week is excluded. Values below retain the workbook’s reported precision. This transparent portfolio method does not replace disease-specific national thresholds.</p><p>The threshold rises after the peak because the rolling baseline incorporates it. Subsequent non-exceedance does not establish that risk has resolved.</p><table><caption>Weekly cholera analysis; “—” means unavailable</caption><thead><tr><th scope="col">EW</th><th scope="col">Cases</th><th scope="col">Deaths</th><th scope="col">Prior mean</th><th scope="col">Threshold</th></tr></thead><tbody>{weekly.map(([week,cases,deaths,mean,threshold])=><tr key={week}><th scope="row">{week}</th><td>{cases}</td><td>{deaths}</td><td>{mean?.toFixed(2)??'—'}</td><td>{threshold?.toFixed(2)??'—'}</td></tr>)}</tbody></table></details></section>
    <section className="intelligenceSection"><p className="eyebrow">06 / Where should attention go?</p><h2>Concentrate the investigation.</h2><p>During EW15–17, Central and East Districts carry the highest operational priority.</p><div className="intelligenceDistricts">{[['Central District',24,'5.33'],['East District',18,'12.00']].map(([name,cases,ratio])=><article key={name}><h3>{name}</h3><div className="intelligenceBarTrack" aria-hidden="true"><span style={{width:`${Number(cases)/24*100}%`}}/></div><p><strong>{cases} cases</strong> · 1 death</p><p><b>{ratio}×</b> immediate baseline</p></article>)}</div><p>Central carried the larger case burden, while East showed the sharper increase relative to baseline.</p><p className="intelligenceNote">Fictional districts. Ratios compare the weekly mean in EW15–17 with EW11–14; they are not population incidence ratios.</p></section>
    <section className="intelligenceSection intelligenceDecisions"><p className="eyebrow">07 / So what?</p><h2>Each finding changes the next action.</h2><dl>{[['Unusual increase','Verify cases'],['Geographic concentration','Prioritize investigation'],['Deaths identified','Review severity and case-management readiness'],['Reporting delays','Strengthen notification'],['Unresolved laboratory status','Follow specimens and results']].map(([finding,action])=><div key={finding}><dt>{finding}</dt><dd><span aria-hidden="true">→ </span>{action}</dd></div>)}</dl></section>
    <section className="intelligenceSection"><p className="eyebrow">08 / Recommended action</p><h2>Verify. Investigate. Reassess.</h2><ol className="intelligencePathway">{[['Verify','0–24 hours','Check cases, onset dates, locations and outcomes; coordinate through the surveillance chain.'],['Investigate','24–72 hours','Assess clustering and common exposures; review case-management readiness.'],['Lab follow-up','0–48 hours','Resolve specimen status and reconcile pending results.'],['Active case search','0–48 hours','Review registers and seek additional cases in priority facilities and communities.'],['Reassess','Within 7 days','Review reporting delays and repeat signal assessment with verified and newly reported cases.']].map(([action,time,note])=><li key={action}><h3>{action}</h3><b>{time}</b><p>{note}</p></li>)}</ol><p className="intelligenceNote">Activities overlap: laboratory follow-up and active case search begin alongside verification and investigation.</p></section>
    <section className="intelligenceSection"><p className="eyebrow">09 / Important interpretation</p><h2>A signal is a reason to investigate.</h2><p className="intelligenceLead">It does not, by itself, confirm an outbreak, prove transmission or establish a common source.</p><details className="intelligenceDetails"><summary>Interpretation and limitations</summary><ul><li>Case verification, epidemiological linkage, laboratory evidence where applicable and field investigation are needed before stronger conclusions.</li><li>No district population denominators are available; district-specific incidence cannot be calculated.</li><li>Incomplete laboratory information and absent exposure/WASH variables limit transmission hypotheses.</li><li>The operational priority index combines burden, growth, deaths and reporting delay. It is not a validated prediction score.</li><li>The simulated dataset demonstrates analytical reasoning, not a real surveillance event.</li></ul></details></section>
    <section className="intelligenceSection"><p className="eyebrow">10 / Tools &amp; capabilities</p><h2>Analysis that supports a decision.</h2><p>Analytical workflow developed in Excel, from preserved source records to quality assessment, epidemiological interpretation and a proportionate action pathway.</p><ul className="intelligenceCapabilities">{capabilities.map(c=><li key={c}>{c}</li>)}</ul><a className="button" href="/#analytics">Back to analytics <span aria-hidden="true">↖</span></a></section>
  </div>
</main>}
